[package]
name = "melvin-ob"
version = "0.1.0"
authors = ["Felix Renzikowski <felix.renzi@outlook.de", "Nicolai Kallis <nicolai.kallis@gmx.de>"]
edition = "2021"

description = "On-Board software MELVIN for the 2024 ESA Computer in a Room Challenge"
license-file = "LICENSE"
repository = "https://github.com/CIARC-CUIYC/melvin-ob"
keywords = []
categories = []

[dependencies]
reqwest = { version = "0.12.9", features = ["json"] }
tokio = { version = "1.0", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
chrono = { version= "0.4", features = ["serde"] }

[lints.clippy]
correctness = "deny"
suspicious = "deny"
cargo = "allow"
perf = "warn"
style = "warn"
complexity = "warn"
pedantic = "warn"





