fn_single_line = true
max_width = 100
single_line_if_else_max_width = 100
single_line_let_else_max_width = 100
attr_fn_like_width = 100
brace_style = 'SameLineWhere'
chain_width = 100
struct_lit_single_line = true
where_single_line = true
condense_wildcard_suffixes = true