name: "Build and Deploy"
on: [push]
jobs:
  build-deploy:
    name: "Build on pi01 and Deploy"
    runs-on: pi01
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          rustflags: "-C target-feature=+crt-static"
          target: x86_64-unknown-linux-gnu
      - name: Build
        run: cargo build --release --target x86_64-unknown-linux-gnu --config target.x86_64-unknown-linux-gnu.linker=\"x86_64-linux-gnu-gcc\"

  build-docker:
    name: "Build docker on arche"
    if: ${{ github.ref == 'refs/heads/main' || contains(github.event.head_commit.message, '[force-container]') }}
    runs-on: arche
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Docker build
        run: docker build . --tag melvin-ob:latest
